export const farewellData = {
//   anish: { name: "Anish", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/anish.png", juniorsComments: [], galleryImages: [] },
  avinash: { name: "Avinash", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/avi.png", juniorsComments: [], galleryImages: [] },
  vardhan: { name: "Vardhan", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/vardhan.png", juniorsComments: [], galleryImages: [] },
  vaishnavi: { name: "Vaishnavi", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/vaishnavi.png", juniorsComments: [], galleryImages: [] },
  srihastha: { name: "Srihastha", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/hastha.png", juniorsComments: [], galleryImages: [] },
  charan: { name: "Charan", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/charan.png", juniorsComments: [], galleryImages: [] },
  "bhanu-satish": { name: "Bhanu Satish", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/bhanu.png", juniorsComments: [], galleryImages: [] },
  adithya: { name: "Adithya", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/adithya.png", juniorsComments: [], galleryImages: [] },
  bindu: { name: "Bindu", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/bindu.png", juniorsComments: [], galleryImages: [] },
  yudhi: { name: "Yudhi", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/yudhi.png", juniorsComments: [], galleryImages: [] },
  "sathvik-k": { name: "Sathvik K", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/sathvikk.png", juniorsComments: [], galleryImages: [] },
  karthikeya: { name: "Karthikeya", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/karthik.png", juniorsComments: [], galleryImages: [] },
  "sathvik-karamshetty": { name: "Sathvik Karamshetty", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/sathvik.png", juniorsComments: [], galleryImages: [] },
  varun: { name: "Varun", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/varunsai.png", juniorsComments: [], galleryImages: [] },
  nipun: { name: "Nipun", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/nipun.png", juniorsComments: [], galleryImages: [] },
  hitesh: { name: "Hitesh", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/hitesh.png", juniorsComments: [], galleryImages: [] },
  ganesh: { name: "Ganesh", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/ganesh.png", juniorsComments: [], galleryImages: [] },
  pranathi: { name: "Pranathi", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/pranathi.png", juniorsComments: [], galleryImages: [] },
  akhileshwar: { name: "Akhileshwar", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/akhil.png", juniorsComments: [], galleryImages: [] },
  snigdha: { name: "Snigdha", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/snigdha.png", juniorsComments: [], galleryImages: [] },
  vimal: { name: "Vimal", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/vimal.png", juniorsComments: [], galleryImages: [] },
  vishal: { name: "Vishal", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/vishal.png", juniorsComments: [], galleryImages: [] },
  harshitha: { name: "Harshitha", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/harshitha.png", juniorsComments: [], galleryImages: [] },
  vishweshwar: { name: "Vishweshwar", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/vishweshwar.png", juniorsComments: [], galleryImages: [] },
  praneesh: { name: "Praneesh", role: "Core Team", quote: '"Data brought us together. These memories keep us."', portrait: "/teamImages/praneesh.png", juniorsComments: [], galleryImages: [] },
};